### ISSUE TITLE
Does not support Inkscape >1.0

### ISSUE THREAD

**Issue by gregdavill** [gregdavill/kicadScripts#15]
Inkscape >1.0 added changes to the arguments that need to be parsed in order to export PNGs.
We'll need to add a way to detect the version of inkscape and adapt what arguments are passed in order to support both the new and distro version of inkscape.

```
python plot_board.py ../FireCam/hardware/FireCam/ButterStick.kicad_pcb
(0, '', 'Copper')
(39, 'Invert', 'SolderMask')
(35, '', 'Paste')
(37, '', 'Silk')
(44, '', 'Edge')
Merging layers...
Rasterizing...
Unknown option --export-png
Traceback (most recent call last):
  File "plot_board.py", line 435, in <module>
    render(plot_plan, project_name + '-Front.png')
  File "plot_board.py", line 369, in render
    final_svg,
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['inkscape', '--export-area=399.251361337:280.666643657:671.150834585:544.440526221', '--export-dpi=1200', '--export-png', '/home/greg/projects/FireCam/hardware/FireCam/plot/ButterStick-Front.png', '--export-background', '#5b4b43', '/home/greg/projects/FireCam/hardware/FireCam/plot/temp/ButterStick-merged.svg']' returned non-zero exit status 1.
```

**Comment by gregdavill** [comment]
This is now fixed
