### ISSUE TITLE
plot_board fails on render

### ISSUE THREAD

**Issue by 4b11b4** [gregdavill/kicadScripts#6]
See output:

```
ab@xps ~/pub/kicadScripts $ python plot_board.py /home/ab/folktek/garden-limited/nano/nano.kicad_pcb
(1, '', 'CopperInner')
Traceback (most recent call last):
  File "plot_board.py", line 420, in <module>
    render(plot_plan, project_name + '-Front.png')
  File "plot_board.py", line 310, in render
    svgData.openSVG(pctl.GetPlotFileName())
  File "plot_board.py", line 70, in openSVG
    root = ET.parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: unbound prefix: line 15, column 0
```

Not sure where to begin with this one.
I tried to:
```pip install --user elementpath```
...but I don't think that was the issue as I didn't get a "no module" error...

Any ideas? Thanks.
plot_gerbers seems to work fine...

**Comment by gregdavill** [comment]
Can you let me know what version of KiCad you're using?
